<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Alf Magne
 * Date: 30.04.12
 * Time: 19:15
 * To change this template use File | Settings | File Templates.
 */
class ChessCountry extends ChessDbModel
{

    protected $dbTableName = 'chess_country';

    protected $definition = array(
        'fields' => array(
            'id' => 'int auto_increment not null primary key',
            'name' => 'varchar(512)'
        ),
        'indexes' => array(),
        'defaultData' => array(
            array('name' => 'Afghanistan'),
            array('name' => 'Albania'),
            array('name' => 'Algeria'),
            array('name' => 'Andorra'),
            array('name' => 'Angola'),
            array('name' => 'Antigua & Deps'),
            array('name' => 'Argentina'),
            array('name' => 'Armenia'),
            array('name' => 'Australia'),
            array('name' => 'Austria'),
            array('name' => 'Azerbaijan'),
            array('name' => 'Bahamas'),
            array('name' => 'Bahrain'),
            array('name' => 'Bangladesh'),
            array('name' => 'Barbados'),
            array('name' => 'Belarus'),
            array('name' => 'Belgium'),
            array('name' => 'Belize'),
            array('name' => 'Benin'),
            array('name' => 'Bhutan'),
            array('name' => 'Bolivia'),
            array('name' => 'Bosnia Herzegovina'),
            array('name' => 'Botswana'),
            array('name' => 'Brazil'),
            array('name' => 'Brunei'),
            array('name' => 'Bulgaria'),
            array('name' => 'Burkina'),
            array('name' => 'Burundi'),
            array('name' => 'Cambodia'),
            array('name' => 'Cameroon'),
            array('name' => 'Canada'),
            array('name' => 'Cape Verde'),
            array('name' => 'Central African Rep'),
            array('name' => 'Chad'),
            array('name' => 'Chile'),
            array('name' => 'China'),
            array('name' => 'Colombia'),
            array('name' => 'Comoros'),
            array('name' => 'Congo'),
            array('name' => 'Congo {Democratic Rep}'),
            array('name' => 'Costa Rica'),
            array('name' => 'Croatia'),
            array('name' => 'Cuba'),
            array('name' => 'Cyprus'),
            array('name' => 'Czech Republic'),
            array('name' => 'Denmark'),
            array('name' => 'Djibouti'),
            array('name' => 'Dominica'),
            array('name' => 'Dominican Republic'),
            array('name' => 'East Timor'),
            array('name' => 'Ecuador'),
            array('name' => 'Egypt'),
            array('name' => 'El Salvador'),
            array('name' => 'Equatorial Guinea'),
            array('name' => 'Eritrea'),
            array('name' => 'Estonia'),
            array('name' => 'Ethiopia'),
            array('name' => 'Fiji'),
            array('name' => 'Finland'),
            array('name' => 'France'),
            array('name' => 'Gabon'),
            array('name' => 'Gambia'),
            array('name' => 'Georgia'),
            array('name' => 'Germany'),
            array('name' => 'Ghana'),
            array('name' => 'Greece'),
            array('name' => 'Grenada'),
            array('name' => 'Guatemala'),
            array('name' => 'Guinea'),
            array('name' => 'Guinea-Bissau'),
            array('name' => 'Guyana'),
            array('name' => 'Haiti'),
            array('name' => 'Honduras'),
            array('name' => 'Hungary'),
            array('name' => 'Iceland'),
            array('name' => 'India'),
            array('name' => 'Indonesia'),
            array('name' => 'Iran'),
            array('name' => 'Iraq'),
            array('name' => 'Ireland {Republic}'),
            array('name' => 'Israel'),
            array('name' => 'Italy'),
            array('name' => 'Ivory Coast'),
            array('name' => 'Jamaica'),
            array('name' => 'Japan'),
            array('name' => 'Jordan'),
            array('name' => 'Kazakhstan'),
            array('name' => 'Kenya'),
            array('name' => 'Kiribati'),
            array('name' => 'Korea North'),
            array('name' => 'Korea South'),
            array('name' => 'Kosovo'),
            array('name' => 'Kuwait'),
            array('name' => 'Kyrgyzstan'),
            array('name' => 'Laos'),
            array('name' => 'Latvia'),
            array('name' => 'Lebanon'),
            array('name' => 'Lesotho'),
            array('name' => 'Liberia'),
            array('name' => 'Libya'),
            array('name' => 'Liechtenstein'),
            array('name' => 'Lithuania'),
            array('name' => 'Luxembourg'),
            array('name' => 'Macedonia'),
            array('name' => 'Madagascar'),
            array('name' => 'Malawi'),
            array('name' => 'Malaysia'),
            array('name' => 'Maldives'),
            array('name' => 'Mali'),
            array('name' => 'Malta'),
            array('name' => 'Marshall Islands'),
            array('name' => 'Mauritania'),
            array('name' => 'Mauritius'),
            array('name' => 'Mexico'),
            array('name' => 'Micronesia'),
            array('name' => 'Moldova'),
            array('name' => 'Monaco'),
            array('name' => 'Mongolia'),
            array('name' => 'Montenegro'),
            array('name' => 'Morocco'),
            array('name' => 'Mozambique'),
            array('name' => 'Myanmar, {Burma}'),
            array('name' => 'Namibia'),
            array('name' => 'Nauru'),
            array('name' => 'Nepal'),
            array('name' => 'Netherlands'),
            array('name' => 'New Zealand'),
            array('name' => 'Nicaragua'),
            array('name' => 'Niger'),
            array('name' => 'Nigeria'),
            array('name' => 'Norway'),
            array('name' => 'Oman'),
            array('name' => 'Pakistan'),
            array('name' => 'Palau'),
            array('name' => 'Panama'),
            array('name' => 'Papua New Guinea'),
            array('name' => 'Paraguay'),
            array('name' => 'Peru'),
            array('name' => 'Philippines'),
            array('name' => 'Poland'),
            array('name' => 'Portugal'),
            array('name' => 'Qatar'),
            array('name' => 'Romania'),
            array('name' => 'Russian Federation'),
            array('name' => 'Rwanda'),
            array('name' => 'St Kitts & Nevis'),
            array('name' => 'St Lucia'),
            array('name' => 'Saint Vincent & the Grenadines'),
            array('name' => 'Samoa'),
            array('name' => 'San Marino'),
            array('name' => 'Sao Tome & Principe'),
            array('name' => 'Saudi Arabia'),
            array('name' => 'Senegal'),
            array('name' => 'Serbia'),
            array('name' => 'Seychelles'),
            array('name' => 'Sierra Leone'),
            array('name' => 'Singapore'),
            array('name' => 'Slovakia'),
            array('name' => 'Slovenia'),
            array('name' => 'Solomon Islands'),
            array('name' => 'Somalia'),
            array('name' => 'South Africa'),
            array('name' => 'South Sudan'),
            array('name' => 'Spain'),
            array('name' => 'Sri Lanka'),
            array('name' => 'Sudan'),
            array('name' => 'Suriname'),
            array('name' => 'Swaziland'),
            array('name' => 'Sweden'),
            array('name' => 'Switzerland'),
            array('name' => 'Syria'),
            array('name' => 'Taiwan'),
            array('name' => 'Tajikistan'),
            array('name' => 'Tanzania'),
            array('name' => 'Thailand'),
            array('name' => 'Togo'),
            array('name' => 'Tonga'),
            array('name' => 'Trinidad & Tobago'),
            array('name' => 'Tunisia'),
            array('name' => 'Turkey'),
            array('name' => 'Turkmenistan'),
            array('name' => 'Tuvalu'),
            array('name' => 'Uganda'),
            array('name' => 'Ukraine'),
            array('name' => 'United Arab Emirates'),
            array('name' => 'United Kingdom'),
            array('name' => 'United States'),
            array('name' => 'Uruguay'),
            array('name' => 'Uzbekistan'),
            array('name' => 'Vanuatu'),
            array('name' => 'Vatican City'),
            array('name' => 'Venezuela'),
            array('name' => 'Vietnam'),
            array('name' => 'Yemen'),
            array('name' => 'Zambia'),
            array('name' => 'Zimbabwe')
        )
    );

    public static function getAll(){
        $ret = array();
        $res = mysql_query("select * from chess_country order by ID");
        while($row = mysql_fetch_assoc($res)){
            $ret[] = array('id' => $row['id'], 'title' => $row['name']);
        }
        return $ret;
    }
}
